apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    longhorn.io/volume-scheduling-error: ''
    pv.kubernetes.io/provisioned-by: driver.longhorn.io
    volume.kubernetes.io/provisioner-deletion-secret-name: ''
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ''
  creationTimestamp: '2025-06-12T22:24:54Z'
  finalizers:
    - external-provisioner.volume.kubernetes.io/finalizer
    - kubernetes.io/pv-protection
    - external-attacher/driver-longhorn-io
  managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:pv.kubernetes.io/provisioned-by: {}
            f:volume.kubernetes.io/provisioner-deletion-secret-name: {}
            f:volume.kubernetes.io/provisioner-deletion-secret-namespace: {}
          f:finalizers:
            .: {}
            v:"external-provisioner.volume.kubernetes.io/finalizer": {}
        f:spec:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:claimRef:
            .: {}
            f:apiVersion: {}
            f:kind: {}
            f:name: {}
            f:namespace: {}
            f:resourceVersion: {}
            f:uid: {}
          f:csi:
            .: {}
            f:driver: {}
            f:fsType: {}
            f:volumeAttributes:
              .: {}
              f:dataEngine: {}
              f:dataLocality: {}
              f:disableRevisionCounter: {}
              f:fromBackup: {}
              f:fsType: {}
              f:numberOfReplicas: {}
              f:staleReplicaTimeout: {}
              f:storage.kubernetes.io/csiProvisionerIdentity: {}
              f:unmapMarkSnapChainRemoved: {}
            f:volumeHandle: {}
          f:persistentVolumeReclaimPolicy: {}
          f:storageClassName: {}
          f:volumeMode: {}
      manager: csi-provisioner
      operation: Update
      time: '2025-06-12T22:24:54Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:status:
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      subresource: status
      time: '2025-06-12T22:24:54Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:longhorn.io/volume-scheduling-error: {}
      manager: longhorn-manager
      operation: Update
      time: '2025-06-12T22:24:54Z'
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:finalizers:
            v:"external-attacher/driver-longhorn-io": {}
      manager: csi-attacher
      operation: Update
      time: '2025-06-12T22:24:56Z'
  name: pvc-124019f3-d324-4053-afd2-59bd9c91068b
  resourceVersion: '1371999'
  uid: 35961167-bd8f-4ad8-b1ed-05dc8a1408c1
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 50Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: repo-data-gitlab-gitaly-0
    namespace: gitlab-o3s
    resourceVersion: '1371455'
    uid: 124019f3-d324-4053-afd2-59bd9c91068b
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeAttributes:
      dataEngine: v1
      dataLocality: disabled
      disableRevisionCounter: 'true'
      fromBackup: ''
      fsType: ext4
      numberOfReplicas: '3'
      staleReplicaTimeout: '30'
      storage.kubernetes.io/csiProvisionerIdentity: 1749742631123-1730-driver.longhorn.io
      unmapMarkSnapChainRemoved: ignored
    volumeHandle: pvc-124019f3-d324-4053-afd2-59bd9c91068b
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: '2025-06-12T22:24:54Z'
  phase: Bound
